name: ec2-creation
on: [push]
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v5

      - name: setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: run init
        run: terraform init
      
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: run plan
        run: terraform plan
      
      - name: run apply
        run: terraform apply -auto-approve
